# debuginfod.ubuntu.com webserver

# redirects to debuginfod service for buildid requests.

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    client_max_body_size 1M;

    autoindex off;

    # proxy debuginfod requests, preserving the /buildid prefix
    # debuginfod API requires: /buildid/BUILDID/{debuginfo,executable,source/PATH}
    # http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
    location ~ ^/(buildid|metrics)(/|$) {
        proxy_pass http://127.0.0.1:8002;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
    }

    location / {
        return 301 https://ubuntu.com/server/docs/service-debuginfod;
    }
}
